FROM openjdk:8u111-jdk-alpine
ADD /Users/ekapolwongnapapan/.jenkins/workspace/CourseService-Pull-Code/target/courseservice-0.0.1-SNAPSHOT.jar
ENTRYPOINT ["java","-jar","/courseservice-0.0.1-SNAPSHOT.jar"]